version: "3.8"
services:
  server1:
    build: .
    # ports:
    #   - "5000:5000"
    networks:
      default:
        ipv4_address: 172.20.1.1
    container_name: server_1

  server2:
    build: .
    # ports:
    #   - "5000:5000"
    networks:
      default:
        ipv4_address: 172.20.1.2
    container_name: server_2

  haproxy:
    image: "haproxy:2.2-alpine"
    ports:
      - 5000:5000
#      - 443:443
    stdin_open: true
    tty: true
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
#      - ./cert.pem:/etc/ssl/certs/site.pem
networks:
  default:
    external:
      name: develop